### ISSUE TITLE
When on settings back button doesn't load Home activity 

### ISSUE THREAD

**Issue by julian-labuschagne** [janpansa/arduino_bluetooth_android#1]
When selecting settings and then pressing the Android back button the application asks to quit the application instead of going to previous or Home activity.

**Comment by janpansa** [comment]
Yes, I need to fix this. In fact, it might be the same for all fragments.
The reason for this is that the fragments are currently all loading into
the same fragment "placeholder" and should rather be loaded individually
into it's own fragment. Not sure if that makes sense. I will possibly start
working on this and the rest on Thursday / Friday.

On Mon, Jul 27, 2015 at 4:14 PM, Julian notifications@github.com wrote:

> When selecting settings and then pressing the Android back button the
> application asks to quit the application instead of going to previous or
> Home activity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/janpansa/arduino_bluetooth_android/issues/1.

## 

Gideon van der Merwe
Jnr. Database Administrator
University of Pretoria
Onderstepoort
0125298470

**Comment by janpansa** [comment]
Ok, just reporting back on this... this behaviour is actually "normal" in the sense of how fragments work inside a drawer. What happens is, the application runs on the main activity which extends activity. The fragments runs inside this activity inside a frame layout. When pressing back, you are actually pressing back on the main activity and thus it loads the menu I created for exiting the app. However, this is not necessarily best practice or most user friendly, since back should, in terms of user experience and users recalling back button functionality from any other software, go back to the previous page, screen thing or whatever. So I am going to try and overwrite the onBack from the fragments and only on the home screen, it will ask to exit, since that is the first fragment that we load. Will report back soon :-)

**Comment by janpansa** [comment]
Looking at this again, I believe the default behaviour, as I have noticed in other apps like gmail, is to return to the "home screen", not the previous screen (as @julian-labuschagne mentioned). So it doesn't matter if I navigated from 1 -> 2 -> 3 and then press back, it should take me back to the first screen. E.g. 1 - > 2 - > 3 then back press takes me to 1. I am going to work on getting this kind of functionality. If anyone disagree, please let me know :)

**Comment by janpansa** [comment]
The issue/enhancement has been implemented. Pressing back from any fragment except home will take you back to home. Pressing back from home will open exit dialog. Pressing Exit from drawer menu will also open exit dialog.
